// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3D-120A2MMZLz0I4Vz-F_6I_owgFIRuY',
    appId: '1:1018881351612:web:47e6f39a38e519230cd5b9',
    messagingSenderId: '1018881351612',
    projectId: 'fir-3b6a5',
    authDomain: 'fir-3b6a5.firebaseapp.com',
    storageBucket: 'fir-3b6a5.appspot.com',
    measurementId: 'G-HQMDQ0QW9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHze7LeN0TbfWa32A6wBkabv288X-coLQ',
    appId: '1:1018881351612:android:51a8f02e813b1e360cd5b9',
    messagingSenderId: '1018881351612',
    projectId: 'fir-3b6a5',
    storageBucket: 'fir-3b6a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_btdY_DTZ7m3qInRxqZFecfCv_YOLZFk',
    appId: '1:1018881351612:ios:c098ea31ca3d8d030cd5b9',
    messagingSenderId: '1018881351612',
    projectId: 'fir-3b6a5',
    storageBucket: 'fir-3b6a5.appspot.com',
    androidClientId: '1018881351612-8srpgbujod9n1rc0v6eiajvc0pp2bpuj.apps.googleusercontent.com',
    iosClientId: '1018881351612-iilir324mgpmhrisbg6umf8ubaauh45t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexfilms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_btdY_DTZ7m3qInRxqZFecfCv_YOLZFk',
    appId: '1:1018881351612:ios:c098ea31ca3d8d030cd5b9',
    messagingSenderId: '1018881351612',
    projectId: 'fir-3b6a5',
    storageBucket: 'fir-3b6a5.appspot.com',
    androidClientId: '1018881351612-8srpgbujod9n1rc0v6eiajvc0pp2bpuj.apps.googleusercontent.com',
    iosClientId: '1018881351612-iilir324mgpmhrisbg6umf8ubaauh45t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexfilms',
  );
}
